# trigger:
  # branches:
    # include:
      # - main

# variables:
  #Variables de entorno
  # ACR_NAME: 'appmysql' # Colocar el nombre de tu ACR
  # IMAGE_NAME: 'dockermysql' # Colocar el Nombre de Imagen
  # SERVICE_CONNECTION_NAME: 'appimages' # Colocar nombre del Service Connection ubicado en Docker Registry-- Azure Container Registry

# jobs:
  # - job: BuildAndPush
    # pool:
      # vmImage: 'ubuntu-latest'
    # steps:
      # - task: Docker@2
        # inputs:
          # command: 'buildAndPush'
          # containerRegistry: '$(SERVICE_CONNECTION_NAME)'
          # repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
          # dockerfile: '**/Dockerfile'
          # tags: |
            # latest
        # displayName: 'Build and Push Docker Image ACR'
        
trigger:
  branches:
    include:
      - main

variables:
  # Variables de entorno
  ACR_NAME: 'examencontainer' # Colocar el nombre de tu ACR
  IMAGE_NAME: 'dockermysql' # Colocar el Nombre de Imagen 
  SERVICE_CONNECTION_NAME: 'examen-devops' # Colocar nombre del Service Connection ubicado en Docker Registry-- Azure Container Registry

jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          containerRegistry: '$(SERVICE_CONNECTION_NAME)'
          repository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
          dockerfile: '**/Dockerfile'
          tags: |
            latest
        displayName: 'Build and Push Docker Image'

